[package]
name = "grind-create3-seed"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = "0.6"
alloy-rlp = "0.3.11"
alloy-sol-types = "0.6"
rayon = "1.7"
hex = "0.4"
hex-literal = "0.4.1"
