[package]
name = "fairy-v1"
version = "0.1.0"
edition = "2021"

[dependencies]
stylus-sdk = { version = "0.4.2", features = ["hostio", "debug"] }
mini-alloc = "0.4.2"

[features]
export-abi = ["stylus-sdk/export-abi"]
#debug = ["stylus-sdk/debug"]

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "s"

[workspace]
