[package]
name = "goblin-program"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
goblin-core = { path = "../goblin-core", default-features = false, features = ["localnet"] }
goblin-hostio = { path = "../goblin-hostio" }
deku = { version = "0.20", default-features = false }
