[package]
name = "goblin-sdk-rs"
version = "0.1.0"
edition = "2021"
description = "SDK for calldata serialization to call goblin-core-v1 Stylus contract"

[lib]
crate-type = ["rlib"]

[dependencies]
goblin-core-v1 = { path = "../goblin-core-v1", default-features = false, features = ["localnet"] }
goblin-macros = { path = "../goblin-macros" }
hex = { version = "0.4", default-features = false, features = ["alloc"] }

# WASM dependencies
wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }

[dev-dependencies]
hex-literal = "0.4.1"

[features]
default = []
std = []
wasm = ["wasm-bindgen", "js-sys"]
