[package]
name = "goblin-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
alloy = "0.11.1"
sqlx = { version = "0.8.3", features = ["sqlite", "runtime-tokio"] }
anyhow = "1.0.96"
dotenvy = "0.15.7"
