use core::marker::PhantomData;

use crate::{
    markets::LotSizePair,
    matching::MatchResult,
    quantities::UnsidedAtoms,
    settlement::local_delta::LocalSenderDelta,
    types::{Base, LegMarker, Pair, PairAccessor, Quote},
};

// The update generated by local sender delta that will be applied on the global delta
//
// The matching logic uses `MatchingLots`. They must be converted into `Atoms`, the unit of
// token balances and settlement.
//
// # Conversion flow
//
// MatchingLots -> Lots -> Atoms / UnsidedAtoms
//
// TODO use sided Atoms here? I ended up reintroducing In: LegMarker to track the side.
pub struct SenderGlobalUpdateV2<In>
where
    In: LegMarker,
    // In::Opposite: LegMarker,
{
    /// Atoms lost by taker, to be deducted from free atoms for side In
    pub free_atoms_in: In::Atoms,

    /// Atoms gained by taker, to be added for side In::Opposite
    pub locked_atoms_out: <In::Opposite as LegMarker>::Atoms,

    /// Atoms of side In::Opposite unlocked on self  trade
    pub atoms_released_by_self_trade: <In::Opposite as LegMarker>::Atoms,
}

pub type SenderUpdatePair = Pair<SenderGlobalUpdateV2<Base>, SenderGlobalUpdateV2<Quote>>;

impl<In> SenderGlobalUpdateV2<In> where In: LegMarker {}

pub struct SenderGlobalUpdate<In: LegMarker> {
    /// Atoms lost by taker, to be deducted from free atoms for side In
    pub free_atoms_in: UnsidedAtoms,

    /// Atoms gained by taker, to be added for side In::Opposite
    pub locked_atoms_out: UnsidedAtoms,

    /// Atoms of side In::Opposite unlocked on self  trade
    pub atoms_released_by_self_trade: UnsidedAtoms,
    _marker: core::marker::PhantomData<In>,
}

impl<In> SenderGlobalUpdate<In>
where
    In: LegMarker
        + PairAccessor<
            <Base as LegMarker>::LotsPerUnit,
            <Quote as LegMarker>::LotsPerUnit,
            Result = In::LotsPerUnit,
        > + PairAccessor<MatchResult<Base>, MatchResult<Quote>, Result = MatchResult<In>>,
    In::Opposite:
        PairAccessor<MatchResult<Base>, MatchResult<Quote>, Result = MatchResult<In::Opposite>>,
{
    pub fn new(sender_delta: &LocalSenderDelta, lot_size_pair: LotSizePair) -> Self {
        let lot_size = *In::get_leg(&lot_size_pair);
        let atoms_per_lot = In::atoms_per_lot(lot_size);

        let delta = In::get_leg(&sender_delta.take_result_pair);
        let delta_opposite = In::Opposite::get_leg(&sender_delta.take_result_pair);

        // Is my logic wrong, and that we are already collecting for the same token?
        // locked_atoms_out and atoms_released_by_self_trade is read from the opposite side
        let free_atoms_in = In::matching_lots_to_atoms_unsided(
            delta.free_matching_lots_in,
            lot_size_pair.base,
            atoms_per_lot,
        );

        let locked_atoms_out = In::matching_lots_to_atoms_unsided(
            delta_opposite.locked_matching_lots_out,
            lot_size_pair.base,
            atoms_per_lot,
        );

        let atoms_released_by_self_trade = In::matching_lots_to_atoms_unsided(
            delta_opposite.released_by_self_trade,
            lot_size_pair.base,
            atoms_per_lot,
        );

        Self {
            free_atoms_in,
            locked_atoms_out,
            atoms_released_by_self_trade,
            _marker: PhantomData,
        }
    }
}
