[package]
name = "goblin-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mini-alloc = "0.7.0"

[profile.release]
opt-level = "s"
strip = true
lto = true
panic = "abort"

[features]
default = []
