[package]
name = "compile-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6"
wasmprinter = "0.2"
wat = "1.0"
brotli2 = "0.3"
wasm-encoder = "0.30"
wasmparser = "0.110"
hex = "0.4"
leb128 = "0.2"
alloy-primitives = "0.8.21"
