[package]
name = "goblin-core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
goblin-hostio = { path = "../goblin-hostio" }
goblin-macros = { path = "../goblin-macros" }
keccak-const = "0.2.0"
hex-literal = "0.4.1"

[features]
default = ["localnet"]
localnet = []
testnet = []
mainnet = []
